// Auto-generated by designsoul-skeleton — do not edit.
import { registerSkeletons } from 'designsoul-skeleton';
import s0 from './profile-card.skeleton.json' with { type: 'json' };

registerSkeletons({
  "profile-card": s0,
});
