// Auto-generated by the DesignSoul Skeleton Generator — do not edit.
import { registerSkeletons } from '../skeleton.js';
import s0 from './profile-card.skeleton.json' assert { type: 'json' };

registerSkeletons({
  "profile-card": s0,
});
