/* designsoul-skeleton/react — thin React wrapper over the <ds-skeleton> element.
   Usage:
     import { Skeleton } from 'designsoul-skeleton/react';
     import 'designsoul-skeleton/css';
     import './skeletons/registry';   // generated by the CLI

     <Skeleton name="profile-card" loading={isLoading} animate="shimmer" transition={300}>
       <ProfileCard data={data} />
     </Skeleton>
*/
import { createElement, useRef, useEffect } from "react";
import "designsoul-skeleton"; // defines the <ds-skeleton> custom element

export function Skeleton({
  name,
  loading,
  animate,
  color,
  darkColor,
  stagger,
  transition,
  children,
  style,
  className,
}) {
  const ref = useRef(null);
  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    if (loading) el.setAttribute("loading", "true");
    else el.removeAttribute("loading");
  }, [loading]);

  return createElement(
    "ds-skeleton",
    {
      ref,
      name,
      animate,
      color,
      "dark-color": darkColor,
      stagger: stagger != null ? String(stagger) : undefined,
      transition: transition != null ? String(transition) : undefined,
      style,
      className,
    },
    children
  );
}

export default Skeleton;
