/* designsoul-skeleton/vue — thin Vue 3 wrapper over the <ds-skeleton> element.
   Usage:
     import Skeleton from 'designsoul-skeleton/vue';
     import 'designsoul-skeleton/css';
     import './skeletons/registry';   // generated by the CLI

     <Skeleton name="profile-card" :loading="isLoading" animate="shimmer" :transition="300">
       <ProfileCard :data="data" />
     </Skeleton>
*/
import { h, defineComponent } from "vue";
import "designsoul-skeleton"; // defines the <ds-skeleton> custom element

export default defineComponent({
  name: "DsSkeleton",
  props: {
    name: { type: String, required: true },
    loading: { type: Boolean, default: false },
    animate: { type: String, default: undefined },
    color: { type: String, default: undefined },
    darkColor: { type: String, default: undefined },
    stagger: { type: [Number, String], default: undefined },
    transition: { type: [Number, String], default: undefined },
  },
  setup(props, { slots }) {
    return () =>
      h(
        "ds-skeleton",
        {
          name: props.name,
          loading: props.loading ? "true" : null,
          animate: props.animate,
          color: props.color,
          "dark-color": props.darkColor,
          stagger: props.stagger != null ? String(props.stagger) : null,
          transition: props.transition != null ? String(props.transition) : null,
        },
        slots.default ? slots.default() : []
      );
  },
});
